export const dormCommunityMap = {
    'bel_air_hall': 'cambridge_c',
    'cambridge_hall': 'cambridge_c',
    'chestertown_hall': 'cambridge_c',
    'cumberland_hall': 'cambridge_c',
    'centreville_hall': 'cambridge_c',
    'denton_hall': 'denton_c',
    'easton_hall': 'denton_c',
    'elkton_hall': 'denton_c',
    'ellicott_hall': 'ellicott_c',
    'hagerstown_hall': 'ellicott_c',
    'la_plata_hall': 'ellicott_c',
    'pyon-chen_hall': 'heritage_c',
    'johnson-whittle_hall': 'heritage_c',
    'anne_arundel_hall': 'northhill_c',
    'caroline_hall': 'northhill_c',
    'carroll_hall': 'northhill_c',
    'dorchester_hall': 'northhill_c',
    'prince_frederick_hall': 'northhill_c',
    'queen_anne\'s_hall': 'northhill_c',
    'st._mary\'s_hall': 'northhill_c',
    'somerset_hall': 'northhill_c',
    'wicomico_hall': 'northhill_c',
    'worcester_hall': 'northhill_c',
    'allegany_hall': 'southhill_c',
    'baltimore_hall': 'southhill_c',
    'calvert_hall': 'southhill_c',
    'cecil_hall': 'southhill_c',
    'charles_hall': 'southhill_c',
    'frederick_hall': 'southhill_c',
    'garrett_hall': 'southhill_c',
    'harford_hall': 'southhill_c',
    'howard_hall': 'southhill_c',
    'kent_hall': 'southhill_c',
    'montgomery_hall': 'southhill_c',
    'prince_george\'s_hall': 'southhill_c',
    'talbot_hall': 'southhill_c',
    'washington_hall': 'southhill_c',
};

export const validApartments = [
    'south_campus_commons',
    'oakland_c',
    'leonardtown_c'
];
